### PR TITLE
Resolves #12: Add Gmail Login

### LINKED ISSUE #12: Add Gmail Login
**I'm submitting a ...**
- [x] feature request

**Would you like to work on the issue?**

Nopes. Open for Claim

### PR DESCRIPTION
**Pull request by aniket1897**
Add **OAuth2 Client ID** for integrating google sign in

### CODE REVIEW

**Comment by aniket1897** [comment]
@sk9331657 Review my PR

**Comment by sk9331657** [comment]
@aniket1897  Make use of single commit rather than these much. Uncommit all your commits till you get Removed errors commit message. Just commmit thar.

**Comment by aniket1897** [comment]
@sk9331657 Where should I put this button??

**Comment by sk9331657** [comment]
@aniket1897 Update.

**Pull request closed without merging**
