### PR TITLE
Added package.json file

### PR DESCRIPTION
**Pull request by aniket1897**
**Installed** require packages required for running backend

### CODE REVIEW

**Comment by sk9331657** [comment]
@aniket1897  Congrats on your first pr.

**Comment by aniket1897** [comment]
Thank you @sk9331657

**Comment by sk9331657** [comment]
@aniket1897  Just create an issue for this and refer it here. I forgot to create the issue.

**Comment by aniket1897** [comment]
Issue #17 resolved. @sk9331657 I would like you close this issue.

**Pull request merged**
