### PR TITLE
Stored data in MongoDB

### PR DESCRIPTION
**Pull request by aniket1897**
**Data collected from Signup page is stored in local mongo database**
Fixes issue #8

### CODE REVIEW

**Comment by sk9331657** [comment]
@aniket1897  You project deployed link on Heroku.

**Comment by aniket1897** [comment]
@sk9331657 Can you tell me how it is done?

**Comment by sk9331657** [comment]
@so just connect your branch on heroku and deploy branch .

**Comment by aniket1897** [comment]
Ok @sk9331657

**Comment by aniket1897** [comment]
@sk9331657  I'm getting an error 
``` @angular/compiler-cli@6.1.10 requires typescript@'>=2.7.2 <2.10' but 3.1.1 was found instead.```

**Comment by aniket1897** [comment]
@sk9331657 Here is the heroku link https://fierce-ridge-85688.herokuapp.com/

**Comment by sk9331657** [comment]
@ankit1897 have you added login facility ??

**Comment by aniket1897** [comment]
Ok @sk9331657

**Comment by aniket1897** [comment]
What route should the server use for handling data sent from login page??

**Comment by sk9331657** [comment]
@aniket1897  api/login will be used for login. If you are familiar with the angular apply  patch for the request from frontend for login feature.

**Comment by aniket1897** [comment]
@sk9331657 All implementation is done. Just I am facing one issue after authentication is successful I'm routing to dash component, the url of the browser is changing but the page does not. After refreshing the page we get to dash .

**Comment by aniket1897** [comment]
@sk9331657 Can u merge the PR?

**Comment by sk9331657** [comment]
@aniket1897  I am testing your branch locally. Just give me time. I will update.

**Comment by sk9331657** [comment]
> @sk9331657 Can u merge the PR?

Your website is not working. If you can run you branch  on Heroku , I will give you  advance credits.

**Comment by aniket1897** [comment]
> > @sk9331657 Can u merge the PR?
> 
> Your website is not working. If you can run you branch on Heroku , I will give you advance credits.

On my machine it is working

**Comment by aniket1897** [comment]
Ok and one more thing my commits are not appearing on KWOC website. If possible can you update?
@sk9331657

**Comment by sk9331657** [comment]
@aniket1897  Can you add the code in the readme to setup mongo because for testing we need to setup mongod ??

**Comment by sk9331657** [comment]
@aniket1897  once done ping me.

**Comment by sk9331657** [comment]
@aniket1897  Also there is repitive line in index.js 
app.use(function (req, res, next) {
	res.setHeader('Access-Control-Allow-Origin', '*');
	res.setHeader('Access-Control-Allow-Methods', 'GET','POST');
	res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');
	res.setHeader('Access-Control-Allow-Credentials', true);
	next();
});
Just remove second occuerenece .

**Comment by aniket1897** [comment]
@sk9331657 Done

**Comment by sk9331657** [comment]
Did you push code??

**Comment by sk9331657** [comment]
I can't find the code.

**Comment by aniket1897** [comment]
@sk9331657 Just did it now

**Comment by sk9331657** [comment]
@aniket1897  Actually , the mongod structure you implemented is running localhost instead setup it on mlabs with free account.

**Comment by aniket1897** [comment]
@sk9331657 Can you merge this PR? As I'm travelling, I will be available for contributions in a few days.

**Comment by sk9331657** [comment]
@aniket1897  pull latest code

**Comment by sk9331657** [comment]
@ankit1897 Update you pr. Make sure to use hosted mongod and also mention sample login credentials store in db for testing.

**Comment by aniket1897** [comment]
@sk9331657 I pulled the latest code and I am finding many errors. Can you please look?

**Comment by sk9331657** [comment]
@aniket1897  Update.

**Comment by aniket1897** [comment]
@sk9331657 Working on it

**Pull request closed without merging**
